FROM golang:1.24rc3-bullseye
WORKDIR /mahiro-lib/user

# COPY config.yaml /mahiro-lib/user/config.yaml
COPY . .

RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go get
RUN go build -o user

EXPOSE 8080
CMD ["./user"]