mysql: 
  host: 127.0.0.1
  port: 3306
  user: mahirolib
  password: mahirolib
  db: mahirolib
lib-proxy:
  host: 127.0.0.1
  port: 7622
#--line.DO NOT DELECT IT--
lib-storage: 
  maxsize: 160000000     #100Mb